import os
import time
os.system('cls')
# cowboy
def yeehaw():
    # 1
    print('                                  ')
    print('                .Ö¨               ')
    print('              .´·\    /^^.        ')
    print('    ◟    ,·---𝜏_\ `Ì^¯ ,. \       ')
    print("    ≡≈~-√       `Ì   /   `'       ")
    print('    ´    "> /`-_    /             ')
    print('         «_//_  7/\\              ')
    print('           `-_\./-./              ')
    print(' _______________________________  ')
    print(' ------------------------=≡=----  ')
    time.sleep(0.05)
    os.system('cls')
    # 2
    print('                                  ')
    print('               _◜Ö¨               ')
    print('             ·´·!.◟_~~^.          ')
    print('     ◟  ,·---\_\`Ì^  ,. \         ')
    print("   .≡≈~≈√       `Ì   /  `-'       ")
    print('     ´   "-_)-__ n  /             ')
    print('           //_ . \ --◝            ')
    print('           ¯`·𝜏.`-\  /            ')
    print(" _____________`'·___´___________  ")
    print(' ------------------=≡=----------  ')
    time.sleep(0.05)
    os.system('cls')
    # 3
    print('                                  ')
    print('                .·Ö¨              ')
    print('              .¨·\   ~`-.         ')
    print('         .··._≥.\`Ì^¯  _ \        ')
    print('   ·≡≈~-√       `)   /´ `◟\      ')
    print('        !    _   n  /             ')
    print('         7 ^l ¨¯·--.`≥¬           ')
    print('        ( / `◟-_ ·-/  \          ')
    print(' ________\.____`·_______`_______  ')
    print(' ---------:≥=≡=-----------------  ')
    time.sleep(0.08)
    os.system('cls')
    # 4
    print('                                  ')
    print('                .·Ö¨              ')
    print('              .¨·\\   _.__        ')
    print('     _     ___ ◟\`Ì^¯¨    \       ')
    print('    }≡≈~{¨¯   ¨¯`Ì    /¯`\|       ')
    print("    ´   /   ._   n   /_  `'       ")
    print("       /.-> / ¨¯¯¨¯'^.¯7          ")
    print('      /´ /.´          Y\          ')
    print(' ____(____`\__________`_`>______  ')
    print(' ------=≡=--≥-------------------  ')
    time.sleep(0.08)
    os.system('cls')
    # 5
    print('                                  ')
    print('                .Ö¨               ')
    print('              .´.`.  _.-v         ')
    print('    ◟  _  __  𝜏_\.Ì^¯    \        ')
    print('    ≡≈¯¨>¨  ¨¯¨ ))    /¯`.l       ')
    print('        (  .-.__n    /    ¯       ')
    print('     .-´_-´     a¯¯┌¨`=,          ')
    print('  ·÷·´/´           |    `\        ')
    print(' ____(_____________|_____`______  ')
    print(' -------------------------------  ')
    time.sleep(0.08)
    os.system('cls')
    # 6
    print('                                  ')
    print('                .Ö¨               ')
    print('              .´.\  _»≈.~.        ')
    print('  ◞◟_  __.__ (_\`Ì^¯    \        ')
    print('   ≡~-~(     ¯  ))   _/¯`.\       ')
    print('     __(  /-._  n    )            ')
    print('    /_.--´    ¨¯>--`.\            ')
    print(' `-√´         .´     `\           ')
    print(' ____________/´________\________  ')
    print(' ------------!------------------  ')
    time.sleep(0.08)
    os.system('cls')
    # 7
    print('                                  ')
    print('                .Ö¨               ')
    print('              .´.\  .w~u.         ')
    print('    ◟   _,..._(_\`Ì^¯  _ \        ')
    print("    ≥≡~¯(       `)   .´ `.'       ")
    print('      ..|  )--_ n   /             ')
    print('     ..¯𝜏¨¯    ¯7/|´              ')
    print("    .'  )   -.__/|´               ")
    print(' ________________|._____________  ')
    print(' -------------------------------- ')
    time.sleep(0.08)
    os.system('cls')
    # 8 
    print('                                  ')
    print('                .Ö¨               ')
    print('              .´.    ~-^.         ')
    print('         ,.-..>_\`Ì^¯ ,. \        ')
    print("    Σ≈~¬(       `Ì   /  `-'       ")
    print('    ¯¯  `>  /._  n  /             ')
    print('       `¯:(´   ¯7 T¯              ')
    print('        `)`.\ >X´|                ')
    print(' ________´__`/´_¯¯______________  ')
    print(' -------------------------------  ')
    time.sleep(0.08)
    os.system('cls')
yeehaw()

def runyeehaw():
    yeehaw()
    yeehaw()
    yeehaw()
    yeehaw()
    yeehaw()
runyeehaw()

#infinite pie attack
def pierun():
    # 1
    print('                                    ')
    print('                                    ')
    print('    /\o                             ')
    print('     /\/                            ')
    print('    /\                              ')
    print('   /  \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 2
    print('                                    ')
    print('                                    ')
    print('     _o                             ')
    print('    //|_                            ')
    print('     |                              ')
    print('    /|                              ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 3
    print('                                    ')
    print('                                    ')
    print('      o              {|             ')
    print('     /_                             ')
    print('     |\                             ')
    print('    / |                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 4
    print('                                    ')
    print('                                    ')
    print('    /\o           {|                ')
    print('     /\/                            ')
    print('    /\                              ')
    print('   /  \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 5 
    print('                                    ')
    print('                                    ')
    print('    /\o        {|                   ')
    print('     /\/                            ')
    print('    /\              {|              ')
    print('   /  \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 6 
    print('                                    ')
    print('                                    ')
    print('    /\o     {|                      ')
    print('     /\/                            ')
    print('    /\           {|                 ')
    print('   /  \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 7 
    print('                                    ')
    print('                                    ')
    print('     _o  {|                         ')
    print('    //|_                            ')
    print('     |        {|                    ')
    print('    /|                              ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 8
    print('                                    ')
    print('     .                              ')
    print('    .o{|             {|             ')
    print('     |_                             ')
    print('     |\    {|                       ')
    print('    / |                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 9
    print('                                    ')
    print('   .                                ')
    print('    _ø|           {|                ')
    print('  ./ |_/                            ')
    print('     |  {|                          ')
    print('    / \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 10 
    print('                                    ')
    print('                                    ')
    print(' .    _ø|      {|                   ')
    print('    .//_/                           ')
    print('.  . {|                             ')
    print('    / \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 11 
    print('                                    ')
    print('                                    ')
    print('       ø|   {|                      ')
    print('  .   /_/                           ')
    print('     {|                             ')
    print(' .  / |                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 12
    print('                                    ')
    print('                                    ')
    print('      ø| {|                          ')
    print('  .   |_|                           ')
    print('     {|                             ')
    print(' .   ||                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 13
    print('                                    ')
    print('     .                              ')
    print('   .  ø||                           ')
    print('    . |/                            ')
    print('.     {|                            ')
    print('      ||                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 14 
    print('                                    ')
    print('   .                                ')
    print(' .   ø| /                           ')
    print('      \/                            ')
    print('  .   {|                            ')
    print('      |\                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 15
    print(' .                                  ')
    print('                                    ')
    print('    ø_ _/                           ')
    print('    \_X__                           ')
    print('.     |                             ')
    print('                                    ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 16
    print('                                    ')
    print('                                    ')
    print('     |                              ')
    print('   ø/                               ')
    print('  _/¯----                           ')
    print('       ¯                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 17
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('     |                              ')
    print('  ø_/_/_                            ')
    print(' _/                                 ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 18
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print(' _o_/__/                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 19
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print(' _o_____                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 20
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('   o_/                              ')
    print('  _/ --_                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 21
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('     o                              ')
    print('      \/_                           ')
    print('     /                              ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 22
    print('                                    ')
    print('                                    ')
    print('                                    ')
    print('     o                              ')
    print('    _|_                             ')
    print('   / |_\                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 23
    print('                                    ')
    print('                                    ')
    print('      o                             ')
    print('    \_|_                            ')
    print('      | |                           ')
    print('     / \                            ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
    # 24
    print('                                    ')
    print('                                    ')
    print('   _ o                              ')
    print('    \|__                            ')
    print('    /\                              ')
    print('   /  \                             ')
    print('                                    ')
    print('  INFINITE PIE ATTACK!!             ')
    time.sleep(0.08)
    os.system('cls')
pierun()

def runpierun():
    pierun()
    pierun()
    pierun()
    pierun()
runpierun()